

const DEBUG = false

const PUBLIC_NEXT_ALGOLIA_ID = "L3RFZXXI90"
const PUBLIC_NEXT_ALGOLIA_KEY = "9ce899f55f87d9fe3938c8eb5f08b44c"

const PUBLIC_NEXT_URL_BACKEND_DEV = "DEV"
const PUBLIC_NEXT_URL_BACKEND_PROD = "PROD"

const PUBLIC_NEXT_URL_FRONTEND_DEV = "http://localhost:3000"
const PUBLIC_NEXT_URL_FRONTEND_PROD = "PROD"

/* GOOGLE */
const RECAPTCHA_KEY = "6LfVlLUqAAAAAHSxM5KYvmr--NOupZdKFu-JYIwf"

// saber si estoy en produccion
const NODE_ENV = process.env.NODE_ENV;
const isProd = NODE_ENV === "production";

const URL_BACKEND = isProd ? PUBLIC_NEXT_URL_BACKEND_PROD : PUBLIC_NEXT_URL_BACKEND_DEV;
const URL_FRONTEND = isProd ? PUBLIC_NEXT_URL_FRONTEND_PROD : PUBLIC_NEXT_URL_FRONTEND_DEV;

export {
    isProd,
    DEBUG,
    PUBLIC_NEXT_ALGOLIA_ID as ALGOLIA_ID,
    PUBLIC_NEXT_ALGOLIA_KEY as ALGOLIA_KEY,
    URL_BACKEND,
    URL_FRONTEND,
    RECAPTCHA_KEY
};