import EmpleadoTypes from "./EmpleadoTypes";

const staticDataFakeEmpleado: EmpleadoTypes[] = [
  {
    id: 1,
    grupo: 1,
    subgrupo: 2,
    seccion: 3,
    concepto_movimiento: "Incorporación",
    cantidad: 5,
    numero_identificacion: "B001-2023-0001",
    nombre: "Laptop",
    marca: "HP",
    modelo: "Pavilion 15",
    serial: "SN123456789",
    incorporaciones: 25000.0,
    desincorporaciones: null,
    observaciones: "Nuevo equipo asignado a personal administrativo.",
  },
  {
    id: 2,
    grupo: 1,
    subgrupo: 4,
    seccion: 2,
    concepto_movimiento: "Desincorporación",
    cantidad: 2,
    numero_identificacion: "B002-2023-0002",
    nombre: "Proyector",
    marca: "Epson",
    modelo: "XGA-100",
    serial: "SN987654321",
    incorporaciones: null,
    desincorporaciones: 1500.0,
    observaciones: "Equipo dañado retirado del inventario.",
  },
  {
    id: 3,
    grupo: 2,
    subgrupo: 3,
    seccion: 1,
    concepto_movimiento: "Incorporación",
    cantidad: 10,
    numero_identificacion: "B003-2023-0003",
    nombre: "Silla de Oficina",
    marca: "Herman Miller",
    modelo: "Aeron",
    serial: "SN567890123",
    incorporaciones: 5000.0,
    desincorporaciones: null,
    observaciones: "Compradas para la sala de reuniones.",
  },
  {
    id: 4,
    grupo: 3,
    subgrupo: 2,
    seccion: 5,
    concepto_movimiento: "Incorporación",
    cantidad: 20,
    numero_identificacion: "B004-2023-0004",
    nombre: "Escritorio",
    marca: "Genérico",
    modelo: "Madera",
    serial: "SN1122334455",
    incorporaciones: 8000.0,
    desincorporaciones: null,
    observaciones: "Equipamiento para aulas.",
  },
  {
    id: 5,
    grupo: 4,
    subgrupo: 1,
    seccion: 6,
    concepto_movimiento: "Desincorporación",
    cantidad: 1,
    numero_identificacion: "B005-2023-0005",
    nombre: "Impresora",
    marca: "Canon",
    modelo: "PIXMA G6020",
    serial: "SN4455667788",
    incorporaciones: null,
    desincorporaciones: 1000.0,
    observaciones: "Equipo obsoleto retirado del uso operativo.",
  },
  {
    id: 6,
    grupo: 4,
    subgrupo: 1,
    seccion: 6,
    concepto_movimiento: "Desincorporación",
    cantidad: 1,
    numero_identificacion: "B005-2023-0005",
    nombre: "Impresora",
    marca: "Canon",
    modelo: "PIXMA G6020",
    serial: "SN4455667788",
    incorporaciones: null,
    desincorporaciones: 101000.0,
    observaciones: "Equipo obsoleto retirado del uso operativo.",
  },
];

export default staticDataFakeEmpleado;
