import EmpleadoTypes from "./EmpleadoTypes";

const staticDataFakeEmpleado: EmpleadoTypes[] = [
  {
    id: 1,
    tipo_empleado: "docente",
    nombres: "Juan",
    apellidos: "Pérez",
    ci: 12345678,
    fecha_nacimiento: "1980-01-01",
    telefono: "1234567890",
    correo_electronico: "juan.perez@example.com",
    fecha_ingreso_mppe: "2010-01-01",
    direccion_de_habitacion: "Calle Falsa 123",
    codigo_cargo: "C001",
    dependencia_nominal: "Dependencia 1",
    estatus: true,
    reposo_permiso: "Ninguno",
    anos_servicio: 10,
    observaciones: "Ninguna",
    titulo_pregrado: "Licenciado en Educación",
    area_docente_especialista: "Matemáticas",
    grado_seccion: "Primaria",
    funcion_trabajo: "Docente",
    acarigua: "",
    titulo_obtenido: "Licenciado",
    inscrito_psuv: true,
    pertenece_movimiento_social: "Movimiento 1",
    carnet_patria_codigo: "CP001",
    carnet_patria_serial: "S001",
    centro_votacion: "Centro 1",
    tipo_voto: "Presencial",
  },
  {
    id: 2,
    tipo_empleado: "docente",
    nombres: "María",
    apellidos: "Gómez",
    ci: 23456789,
    fecha_nacimiento: "1985-02-02",
    telefono: "2345678901",
    correo_electronico: "maria.gomez@example.com",
    fecha_ingreso_mppe: "2011-02-02",
    direccion_de_habitacion: "Avenida Siempre Viva 456",
    codigo_cargo: "C002",
    dependencia_nominal: "Dependencia 2",
    estatus: true,
    reposo_permiso: "Ninguno",
    anos_servicio: 9,
    observaciones: "Ninguna",
    titulo_pregrado: "Licenciado en Educación",
    area_docente_especialista: "Ciencias",
    grado_seccion: "Secundaria",
    funcion_trabajo: "Docente",
    acarigua: "",
    titulo_obtenido: "Licenciado",
    inscrito_psuv: false,
    pertenece_movimiento_social: "Movimiento 2",
    carnet_patria_codigo: "CP002",
    carnet_patria_serial: "S002",
    centro_votacion: "Centro 2",
    tipo_voto: "Presencial",
  },
  {
    id: 3,
    tipo_empleado: "obrero",
    nombres: "Carlos",
    apellidos: "López",
    ci: 34567890,
    fecha_nacimiento: "1990-03-03",
    telefono: "3456789012",
    correo_electronico: "carlos.lopez@example.com",
    fecha_ingreso_mppe: "2012-03-03",
    direccion_de_habitacion: "Calle Principal 789",
    codigo_cargo: "C003",
    dependencia_nominal: "Dependencia 3",
    estatus: true,
    reposo_permiso: "Ninguno",
    anos_servicio: 8,
    observaciones: "Ninguna",
    titulo_pregrado: "",
    area_docente_especialista: "",
    grado_seccion: "",
    funcion_trabajo: "Obrero",
    acarigua: "Acarigua 1",
    titulo_obtenido: "Bachiller",
    inscrito_psuv: true,
    pertenece_movimiento_social: "Movimiento 3",
    carnet_patria_codigo: "CP003",
    carnet_patria_serial: "S003",
    centro_votacion: "Centro 3",
    tipo_voto: "Presencial",
  },
  {
    id: 4,
    tipo_empleado: "obrero",
    nombres: "Ana",
    apellidos: "Martínez",
    ci: 45678901,
    fecha_nacimiento: "1995-04-04",
    telefono: "4567890123",
    correo_electronico: "ana.martinez@example.com",
    fecha_ingreso_mppe: "2013-04-04",
    direccion_de_habitacion: "Avenida Central 101",
    codigo_cargo: "C004",
    dependencia_nominal: "Dependencia 4",
    estatus: true,
    reposo_permiso: "Ninguno",
    anos_servicio: 7,
    observaciones: "Ninguna",
    titulo_pregrado: "",
    area_docente_especialista: "",
    grado_seccion: "",
    funcion_trabajo: "Obrero",
    acarigua: "Acarigua 2",
    titulo_obtenido: "Bachiller",
    inscrito_psuv: false,
    pertenece_movimiento_social: "Movimiento 4",
    carnet_patria_codigo: "CP004",
    carnet_patria_serial: "S004",
    centro_votacion: "Centro 4",
    tipo_voto: "Presencial",
  },
  {
    id: 5,
    tipo_empleado: "administrativos",
    nombres: "Luis",
    apellidos: "Hernández",
    ci: 56789012,
    fecha_nacimiento: "1988-05-05",
    telefono: "5678901234",
    correo_electronico: "luis.hernandez@example.com",
    fecha_ingreso_mppe: "2014-05-05",
    direccion_de_habitacion: "Calle Secundaria 202",
    codigo_cargo: "C005",
    dependencia_nominal: "Dependencia 5",
    estatus: true,
    reposo_permiso: "Ninguno",
    anos_servicio: 6,
    observaciones: "Ninguna",
    titulo_pregrado: "Licenciado en Educación",
    area_docente_especialista: "Historia",
    grado_seccion: "Primaria",
    funcion_trabajo: "Docente",
    acarigua: "",
    titulo_obtenido: "Licenciado",
    inscrito_psuv: true,
    pertenece_movimiento_social: "Movimiento 5",
    carnet_patria_codigo: "CP005",
    carnet_patria_serial: "S005",
    centro_votacion: "Centro 5",
    tipo_voto: "Presencial",
  },
];

export default staticDataFakeEmpleado;
